version: '3.7'

services:

  postgres:
    image: postgres:12.3-alpine
    container_name: qdops-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qdops
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
    ports:
      - 5432:5432

  rabbitmq:
    image: library/rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres-data:
  rabbitmq: